kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: gcr.io/google_containers/spark-master:1.5.1_v2
          env:
            - name: SPARK_EXECUTOR_MEMORY
              value: 128m
            - name: SPARK_DAEMON_MEMORY
              value: 256m
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
