kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: gcr.io/google_containers/zeppelin:v0.5.5_v2
          env:
            - name: SPARK_EXECUTOR_MEMORY
              value: 128m
            - name: SPARK_WORKER_MEMORY
              value: 256m
            - name: SPARK_DAEMON_MEMORY
              value: 256m
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - containerPort: 4040
              hostPort: 4040
              protocol: TCP
          resources:
            requests:
              cpu: 100m
