kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark-worker:1.5.1_v2
          env:
            - name: SPARK_EXECUTOR_MEMORY
              value: 128m
            - name: SPARK_DAEMON_MEMORY
              value: 256m
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
